StringLiterals:
  EnforcedStyle: double_quotes
  Enabled: true

AllCops:
  Exclude:
    - db/**/*
    - config/**/*
    - script/**/*
    - vendor/**/*
    - bin/**/*
    - Rakefile
    - spec/**/*

  TargetRubyVersion: 2.6.3

Rails:
  Enabled: true
